package patterns.scope

enum class ScopeErrors {
    ACCESS_TO_GLOBAL_AREA_ELEMENTS,
    RELATIVE_POSITION_OF_ELEMENTS,
    ACCESS_TO_CLASS_ELEMENTS,
    ACCESS_TO_ELEMENTS_FROM_PARENT_THROUGH_NAMESPACE_ID,
    PREFIX_NAMED,
    ACCESS_TO_NOT_STATIC_ELEMENTS_FROM_STATIC_SCOPE,
    ABSENT_GENERAL_CONTEXT,
    OVERLAPPING
}